export default [
  { type: 'hr' },
  {
    title: 'Components',
    to: '/components',
    icon: 'fas fa-cube',
    submenu: [
      { title: 'App', to: '/app' },
      { title: 'AppBar', to: '/app-bar' },
      { title: 'Action Page', to: '/action-page' },
      { title: 'Button', to: '/button' },
      { title: 'Collection', to: '/collection' },
      { title: 'Collection Group', to: '/collection-group' },
      { title: 'Collection Item', to: '/collection-item' },
      { title: 'Dialog', to: '/dialog' },
      { title: 'Full Page Loading', to: '/full-page-loading' },
      { title: 'Sprite', to: '/sprite' },
      { title: 'Icon', to: '/icon' },
      { title: 'Input', to: '/input' },
      { title: 'Row', to: '/row' },
      { title: 'Printable', to: '/printable' },
      { title: 'Progress', to: '/progress' },
      { title: 'Range', to: '/range' },
      { title: 'Switch', to: '/switch' },
    ],
  },
  { type: 'hr' },
  {
    title: 'API Nativa',
    to: '/native',
    icon: 'fas fa-microchip',
    submenu: [
      { title: 'App', to: '/app' },
      { title: 'Cookie', to: '/cookie' },
      { title: 'Http', to: '/http' },
      { title: 'Keyboard', to: '/native/keyboard' },
      { title: 'Merchant', to: '/merchant' },
      { title: 'Payment', to: '/payment' },
      { title: 'Printer', to: '/printer' },
      { title: 'Signal', to: '/signal' },
      { title: 'System', to: '/system' },
    ],
  },
]
